export let listGroup = [
    {"name": "Program 1",
    "up_coming_events": 3, 
    "post": 29, 
    "last_event": "17/02/2023", 
    },
    {"name": "Program 2",
    "up_coming_events": 3, 
    "post": 29, 
    "last_event": "17/02/2023", 
    },
    {"name": "Program 3",
    "up_coming_events": 3, 
    "post": 29, 
    "last_event": "17/02/2023", 
    },
    {"name":"Program 4",
    "up_coming_events": 3, 
    "post": 29, 
    "last_event": "17/02/2023", 
    },
    {"name": "Program 5",
    "up_coming_events": 3, 
    "post": 29, 
    "last_event": "17/02/2023", 
    },
    {"name": "Program 6",
    "up_coming_events": 3, 
    "post": 29, 
    "last_event": "17/02/2023", 
    },
]